# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ./head
      - uses: actions/checkout@v2
        with:
          ref: main
          path: ./base
    
      - name: OpenAPI Diff in PR
        uses: yaos/openapi-diff-action@v1.1.4
        with:
          # Your GitHub token to allow the action to create PR comments
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base_spec: ./base/api.yaml
          head_spec: ./head/api.yaml
